# Generated by Django 4.0.dev20210722095828 on 2021-08-04 13:55

import django.core.validators
from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeetimelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimelog',
            name='time',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(validators=[employees.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(validators=[employees.validators.validate_id]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, validators=[employees.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Please input a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employeetimelog',
            name='date',
            field=models.CharField(default='01/01/2021', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeetimelog',
            name='employee_id',
            field=models.IntegerField(validators=[employees.validators.validate_id]),
        ),
    ]
