# Generated by Django 4.0.dev20210722095828 on 2021-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeetimelog_time_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimelog',
            name='time',
        ),
        migrations.AlterField(
            model_name='employeetimelog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
